on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test a post tweet action
    steps:
      - name: Notion post fetcher
        id: notion-post-fetcher
        uses: raycast-jp/notion-post-fetcher@v0.0.2
        with:
          targetDate: "2024-09-03"
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db-id: ${{ secrets.NOTION_DB_ID }}
      - name: Print Output Tweet
        id: output-tweet
        run: echo "${{ steps.test-action.outputs.tweet }}"
      - name: Post tweet
        id: tweetx
        uses: noweh/post-tweet-v2-action@v1.0
        with:
          message: ${{ steps.test-action.outputs.tweet }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
