on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  xpost:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    name: A job to test a post tweet action
    steps:
      - name: Get current date
        id: get-date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Notion post fetcher
        id: notion-post-fetcher
        uses: raycast-jp/notion-post-fetcher@v0.0.2
        with:
          targetDate: ${{ env.CURRENT_DATE }}
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db-id: ${{ secrets.NOTION_DB_ID }}
      - name: Print Output Tweet
        id: output-tweet
        run: echo "${{ steps.notion-post-fetcher.outputs.tweet }}"
      - name: Post tweet
        id: tweetx
        uses: raycast-jp/post-tweet-v2-action@v0.0.3
        with:
          message: ${{ steps.notion-post-fetcher.outputs.tweet }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - name: Print Output Published TweetID
        id: output-published-tweet-id
        run: echo "${{ steps.tweetx.outputs.tweetID }}"
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "只今ツイートしましたのでいいね、リツイートなどリアクションお願いします！！\nhttps://x.com/Raycast0731/status/${{ steps.tweetx.outputs.tweetID }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Notify error via slack
        if: failure() 
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "投稿に失敗しました。エラー内容を確認してください: ${{ steps.tweetx.outputs.postFailed }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
